[build-system]
requires = ["setuptools >= 61.0", "autosemver"]
# build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.12"
dependencies = [
    "autosemver",
    "boto3>=1.34.138",
    "config>=0.5.1",
    "moto>=5.0.10",
    "polars>=1.1.0",
    "pyarrow>=17.0.0",
    "pydantic>=2.8.2",
]
name = "dritimeseriesprocessor"
dynamic = ["version"]
authors = [
    {name = "Dom Ginger", email = "domgin@ceh.ac.uk"},
    {name = "Nathan Shaw", email = "natsha@ceh.ac.uk"},
    {name = "Lewis Chambers", email = "lewcha@ceh.ac.uk"},
    {name = "Rod Scott", email = "rjsc@ceh.ac.uk"},
    {name = "Simon Stanley", email = "simsta@ceh.ac.uk"},
    {name = "Richard Smith", email = "ricsmi@ceh.ac.uk"},
]
description = "Timeseries processor service for FDRI."
readme = "README.md"
license = {text = "NO LICENSE"}

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "parameterized"]
docs = ["sphinx", "sphinx-copybutton", "sphinx-rtd-theme"]
lint = ["ruff"]
dev = ["dritimeseriesprocessor[test,docs,lint]"]

[tool.setuptools.dynamic]
version = { attr = "dritimeseriesprocessor.__version__" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["dritimeseriesprocessor*"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.pytest.ini_options]
addopts = "--cov=dritimeseriesprocessor"
markers = [
    "slow: Marks slow tests",
]

filterwarnings = [
    "ignore::DeprecationWarning:autosemver.*:",
    "ignore::DeprecationWarning:pkg_resources.*:",
]

[tool.coverage.run]
omit = ["*__init__.py"]

[tool.ruff]
src = ["src", "tests"]
include = ["src/**.py"]
line-length = 120

[tool.ruff.lint]
select = ["F", "E", "W", "A", "PLC", "PLE", "PLW", "I", "N816", "ANN001", "ANN201", "ANN202", "ANN205", "ANN206"]

[tool.ruff.lint.flake8-type-checking]
strict = true
[tool.pdm]
