on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
      
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read


jobs:

  test-python:
    uses: NERC-CEH/dri-cicd/.github/workflows/test-python.yml@main
    with:
      coverage_threshold: 90

  build-docs:
    uses: NERC-CEH/dri-cicd/.github/workflows/build-docs.yml@main

  deploy-docs:
    uses: NERC-CEH/dri-cicd/.github/workflows/deploy-docs.yml@main
    with:
      pages_artifact_name: pages-artifact